@IsTest
private class StringDirectionalSortCriterionTest {
    @IsTest
    public static void testAscendingNullsFirst() {



//        SortCriterion criterion = new StringDirectionalSortCriterion('attribute');
//        System.assertEquals(0, criterion.compare('Alex', 'Alex'));
//        System.assertEquals(0, criterion.compare(null, null));
//        System.assertEquals(-1, criterion.compare(null, 'Alex'));
//        System.assertEquals(1, criterion.compare('Alex', null));
//        System.assertEquals(-1, criterion.compare('Alex', 'Boris'));
//        System.assertEquals(1, criterion.compare('Boris', 'Alex'));
    }
}
